spring:
  application:
    name: spring_security_oauth

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/spring_security_oauth2?serverTimezone=UTC&characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: create


  security:
    oauth2:
      client:
        registration:

          google:
            client-name: google
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email

          naver:
            client-name: naver
            client-id: ${naver-client-id}
            client-secret: ${naver-client-secret}
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


