spring:
  application:
    name: spring_security_oauth

  security:
    oauth2:
      client:
        registration:

          google:
            client-name: google
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email

          naver:
            client-name: naver
            client-id: ${naver-client-id}
            client-secret: ${naver-client-secret}
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


